---
title: 'Ecology Workshop: Project Proposal'
author: "Marbelys Garriga"
date: "1/10/2020"
output: html_document
---

## Research Statement
  Mangrove forests act as an essential nutrient cycling ecosystem in tropical and subtropical coastal areas. The productivity of this ecological function has been decreasing as forests are both naturally and anthropogenically disturbed, subsequently affecting the current global mangrove cover. Mangrove research usually focuses on measuring and monitoring ecologically important forests often undermining urban smaller patches. However, in urban areas where mangroves have been deforested for developement, ramainding patches are still productive enough to affect nutrient fluxes in the targeted watershed. Therefore it is beneficial to measure how productive these patches are and compare them to well studied fringe forests in the same watershed.   

## Objectives
1. To compare CNP data of soils and mangrove productivity of urban patches with fringe forests
2. To spacially distribute mangrove patches nutrient fluxes with DERM WQ sampling well data in Biscayne Bay 
3. To project nutrient budgets for the next 5 years with and without urban mangroves

## Hypotheses
1. Urban patch mangrove soil CNP will be comparable to larger mangrove forest CNP when size is factored
2. DERM water quality data is lower in TN and TP near urban mangrove patches 
3. Biscayne Bay will be more eutrophied if these urban mangrove patches disappeared

## Datasets
Nutrient CNP of Urban Mangroves (Own dataset)
DERM Water Quality data from Biscayne Bay Wells nearby cocoplum and matheson hammock patches

## Statistical Analysis
Multiple Regression analysis of CNP in urban patches and fringe forests
